; RUN: llc < %s -mtriple=i386-unknown-unknown | FileCheck %s

; ---- from 2008-02-14-BitMiscompile.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define i32 @test_g183m0(i1 %A) {
; CHECK-LABEL: test_g183m0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    andl $1, %eax
; CHECK-NEXT:    negl %eax
; CHECK-NEXT:    movzbl %al, %eax
; CHECK-NEXT:    retl
  %B = zext i1 %A to i32
  %C = sub i32 0, %B
  %D = and i32 %C, 255
  ret i32 %D
}

; ---- from select-neg.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

@value1 = external hidden constant i32

define i32 @function_g183m1(i32 %arg1) {
; CHECK-LABEL: function_g183m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl $value1, %eax
; CHECK-NEXT:    xorl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    negl %eax
; CHECK-NEXT:    retl
entry:
  %0 = xor i32 %arg1, xor (i32 ptrtoint (ptr @value1 to i32), i32 -1)
  %.neg = add i32 %0, 1
  ret i32 %.neg
}

; ---- from sibcall-3.ll ----
; PR7193

define void @t1_g183m2(ptr inreg %dst, ptr inreg %src, ptr inreg %len) nounwind {
; CHECK-LABEL: t1_g183m2:
; CHECK: calll 0
  tail call void null(ptr inreg %dst, ptr inreg %src, ptr inreg %len) nounwind
  ret void
}

define void @t2_g183m2(ptr inreg %dst, ptr inreg %src, ptr inreg %len) nounwind {
; CHECK-LABEL: t2_g183m2:
; CHECK: jmpl
  tail call void null(ptr inreg %dst, ptr inreg %src) nounwind
  ret void
}

; ---- from urem-i8-constant.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; computeKnownBits determines that we don't need a mask op that is required in the general case.

define i8 @foo_g183m3(i8 %tmp325) {
; CHECK-LABEL: foo_g183m3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    imull $111, %eax, %ecx
; CHECK-NEXT:    shrl $12, %ecx
; CHECK-NEXT:    leal (%ecx,%ecx,8), %edx
; CHECK-NEXT:    leal (%ecx,%edx,4), %ecx
; CHECK-NEXT:    subb %cl, %al
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retl
  %t546 = urem i8 %tmp325, 37
  ret i8 %t546
}
