; RUN: llc -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

; ---- from pr28472.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define float @same_dynamic_index_fp_vector_type_g101m0(float %val, i32 %idx) {
; CHECK-LABEL: same_dynamic_index_fp_vector_type_g101m0:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    retq
bb:
  %tmp0 = insertelement <4 x float> undef, float %val, i32 %idx
  %tmp1 = extractelement <4 x float> %tmp0, i32 %idx
  ret float %tmp1
}

; ---- from pr55846.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; After legalization, this could be: "i8 truncate (i64 AssertZext X, Type: i9)"
; The AssertZext does not add information, so it should be eliminated,
; but that must not trigger a compile-time assert.

define void @test_g101m1(ptr %p) {
; CHECK-LABEL: test_g101m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl $256, %eax # imm = 0x100
; CHECK-NEXT:    movq %rax, (%rdi)
; CHECK-NEXT:    retq
  %sel = select i1 true, i64 256, i64 0
  br label %bb2

bb2:
  store i64 %sel, ptr %p, align 4
  %load = load <2 x i1>, ptr %p, align 1
  br label %bb3

bb3:
  %use = add <2 x i1> %load, zeroinitializer
  ret void
}

; ---- from select-of-load-poison.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6

; Make sure there is an and 1, otherwise a case where the select condition
; was poison could result in an out of bounds read instead.
define i32 @test_g101m2(i32 %x, ptr %p) {
; CHECK-LABEL: test_g101m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    andl $1, %edi
; CHECK-NEXT:    movl 4(%rsi,%rdi,4), %eax
; CHECK-NEXT:    retq
  %p1 = getelementptr i8, ptr %p, i64 4
  %v1 = load i32, ptr %p1
  %p2 = getelementptr i8, ptr %p, i64 8
  %v2 = load i32, ptr %p2
  %c = trunc nuw i32 %x to i1
  %v = select i1 %c, i32 %v2, i32 %v1
  ret i32 %v
}
