; RUN: llc -mtriple=x86_64-unknown-linux-gnu %s -o - | FileCheck %s

; ---- from pr37820.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

@a = external dso_local local_unnamed_addr global i64, align 8
@c = external dso_local local_unnamed_addr global i64, align 8
@b = external dso_local local_unnamed_addr global i64, align 8

; Should generate a 16-bit load

define void @foo_g102m0() {
; CHECK-LABEL: foo_g102m0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movzwl a+6(%rip), %eax
; CHECK-NEXT:    movq %rax, b(%rip)
; CHECK-NEXT:    retq
entry:
  %0 = load i64, ptr @a, align 8
  %1 = load i64, ptr @c, align 8
  %and = and i64 %1, -16384
  %add = add nsw i64 %and, 4503359447364223024
  %shr = lshr i64 %0, %add
  %conv1 = and i64 %shr, 4294967295
  store i64 %conv1, ptr @b, align 8
  ret void
}

; ---- from pr40737.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define i8 @_BitScanForward_g102m1(ptr nocapture %Index, i32 %Mask) {
; CHECK-LABEL: _BitScanForward_g102m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    bsfl %esi, %ecx
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    setne %al
; CHECK-NEXT:    movl %ecx, (%rdi)
; CHECK-NEXT:    retq
entry:
  %0 = tail call { i8, i32 } asm "bsf$(l $2,$1 $| $1,$2$)", "={@ccnz},=r,r,~{dirflag},~{fpsr},~{flags}"(i32 %Mask)
  %asmresult = extractvalue { i8, i32 } %0, 0
  %asmresult1 = extractvalue { i8, i32 } %0, 1
  store i32 %asmresult1, ptr %Index, align 4
  ret i8 %asmresult
}
