; RUN: llc < %s -mtriple=i686-- -x86-asm-syntax=intel | FileCheck %s

; ---- from extend.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

@G1_g226m0 = internal global i8 0              ; <ptr> [#uses=1]
@G2_g226m0 = internal global i8 0              ; <ptr> [#uses=1]

define i16 @test1_g226m0() {
; CHECK-LABEL: test1_g226m0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzx eax, byte ptr [G1_g226m0]
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    ret
        %tmp.0 = load i8, ptr @G1_g226m0           ; <i8> [#uses=1]
        %tmp.3 = zext i8 %tmp.0 to i16          ; <i16> [#uses=1]
        ret i16 %tmp.3
}

define i16 @test2_g226m0() {
; CHECK-LABEL: test2_g226m0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movsx eax, byte ptr [G2_g226m0]
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    ret
        %tmp.0 = load i8, ptr @G2_g226m0           ; <i8> [#uses=1]
        %tmp.3 = sext i8 %tmp.0 to i16          ; <i16> [#uses=1]
        ret i16 %tmp.3
}

; ---- from overlap-shift.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

;; X's live range extends beyond the shift, so the register allocator
;; cannot coalesce it with Y.  Because of this, a copy needs to be
;; emitted before the shift to save the register value before it is
;; clobbered.  However, this copy is not needed if the register
;; allocator turns the shift into an LEA.  This also occurs for ADD.

; Check that the shift gets turned into an LEA.

@G = external dso_local global i32                ; <ptr> [#uses=1]

define i32 @test1_g226m1(i32 %X) {
; CHECK-LABEL: test1_g226m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mov eax, dword ptr [esp + 4]
; CHECK-NEXT:    lea ecx, [4*eax]
; CHECK-NEXT:    mov dword ptr [G], ecx
; CHECK-NEXT:    ret
        %Z = shl i32 %X, 2              ; <i32> [#uses=1]
        store volatile i32 %Z, ptr @G
        ret i32 %X
}
