; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=skx | FileCheck %s

; ---- from pr43507.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define <8 x i1> @ham_g381m0(i64 %arg) {
; CHECK-LABEL: ham_g381m0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andb $1, %dil
; CHECK-NEXT:    negb %dil
; CHECK-NEXT:    kmovd %edi, %k0
; CHECK-NEXT:    vpmovm2w %k0, %xmm0
; CHECK-NEXT:    retq
  %tmp = trunc i64 %arg to i1
  %tmp1 = insertelement <8 x i1> undef, i1 %tmp, i32 0
  %tmp2 = shufflevector <8 x i1> %tmp1, <8 x i1> undef, <8 x i32> zeroinitializer
  ret <8 x i1> %tmp2
}

; ---- from pr43509.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define <8 x i8> @foo_g381m1(<8 x float> %arg) {
; CHECK-LABEL: foo_g381m1:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; CHECK-NEXT:    vcmpltps %ymm1, %ymm0, %k1
; CHECK-NEXT:    vcmpgtps {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to8}, %ymm0, %k1 {%k1}
; CHECK-NEXT:    vmovdqu8 {{.*#+}} xmm0 {%k1} {z} = [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
bb:
  %tmp = xor <8 x i8> zeroinitializer, <i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1, i8 1>
  %tmp1 = fcmp reassoc nsz contract ogt <8 x float> %arg, <float 8.000000e+00, float 8.000000e+00, float 8.000000e+00, float 8.000000e+00, float 8.000000e+00, float 8.000000e+00, float 8.000000e+00, float 8.000000e+00>
  %tmp2 = zext <8 x i1> %tmp1 to <8 x i8>
  %tmp3 = and <8 x i8> %tmp, %tmp2
  %tmp4 = fcmp reassoc nsz contract ogt <8 x float> zeroinitializer, %arg
  %tmp5 = or <8 x i1> zeroinitializer, %tmp4
  %tmp6 = zext <8 x i1> %tmp5 to <8 x i8>
  %tmp7 = and <8 x i8> %tmp3, %tmp6
  ret <8 x i8> %tmp7
}
