; RUN: llc -mtriple=x86_64-linux -fast-isel -show-mc-encoding < %s | FileCheck %s

; ---- from add32ri8.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2

; pr22854
define void @foo_g77m0(ptr %s, i32 %x) {
; CHECK-LABEL: foo_g77m0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addl $42, %esi # encoding: [0x83,0xc6,0x2a]
; CHECK-NEXT:    movl %esi, (%rdi) # encoding: [0x89,0x37]
; CHECK-NEXT:    retq # encoding: [0xc3]
  %y = add nsw i32 %x, 42
  store i32 %y, ptr %s, align 4
  ret void
}

; ---- from fast-isel-sext.ll ----
; CHECK-LABEL: f_g77m1:
; CHECK:       addl $-2, %eax         # encoding: [0x83,0xc0,0xfe]
define i32 @f_g77m1(ptr %y) {
  %x = load i32, ptr %y
  %dec = add i32 %x, -2
  ret i32 %dec
}
