; RUN: llc < %s -mtriple=i686-- -mattr=+sse2

; ---- from 2006-05-17-VectorArg.ll ----
define <4 x float> @opRSQ_g196m0(<4 x float> %a) nounwind {
entry:
	%tmp2 = extractelement <4 x float> %a, i32 3		; <float> [#uses=2]
	%abscond = fcmp oge float %tmp2, -0.000000e+00		; <i1> [#uses=1]
	%abs = select i1 %abscond, float %tmp2, float 0.000000e+00		; <float> [#uses=1]
	%tmp3 = tail call float @llvm.sqrt.f32( float %abs )		; <float> [#uses=1]
	%tmp4 = fdiv float 1.000000e+00, %tmp3		; <float> [#uses=1]
	%tmp11 = insertelement <4 x float> zeroinitializer, float %tmp4, i32 3		; <<4 x float>> [#uses=1]
	ret <4 x float> %tmp11
}

declare float @llvm.sqrt.f32(float)

; ---- from 2007-06-29-VecFPConstantCSEBug.ll ----
define void @test_g196m1(ptr %arg) {
	%tmp89 = getelementptr <4 x float>, ptr %arg, i64 3
	%tmp1144 = fsub <4 x float> < float -0.000000e+00, float -0.000000e+00, float -0.000000e+00, float -0.000000e+00 >, zeroinitializer
	store <4 x float> %tmp1144, ptr null
	%tmp1149 = load <4 x float>, ptr %tmp89
	%tmp1150 = fsub <4 x float> < float -0.000000e+00, float -0.000000e+00, float -0.000000e+00, float -0.000000e+00 >, %tmp1149
	store <4 x float> %tmp1150, ptr %tmp89
	ret void
}

; ---- from 2008-03-25-TwoAddrPassBug.ll ----
define void @t_g196m2() {
entry:
	%tmp455 = shufflevector <4 x float> zeroinitializer, <4 x float> undef, <4 x i32> < i32 1, i32 0, i32 3, i32 2 >		; <<4 x float>> [#uses=1]
	%tmp457 = fmul <4 x float> zeroinitializer, %tmp455		; <<4 x float>> [#uses=2]
	%tmp461 = shufflevector <4 x float> %tmp457, <4 x float> undef, <4 x i32> zeroinitializer		; <<4 x float>> [#uses=1]
	%tmp465 = shufflevector <4 x float> %tmp457, <4 x float> undef, <4 x i32> < i32 1, i32 1, i32 1, i32 1 >		; <<4 x float>> [#uses=1]
	%tmp466 = fsub <4 x float> %tmp461, %tmp465		; <<4 x float>> [#uses=1]
	%tmp536 = shufflevector <4 x float> zeroinitializer, <4 x float> %tmp466, <4 x i32> < i32 0, i32 4, i32 1, i32 5 >		; <<4 x float>> [#uses=1]
	%tmp542 = shufflevector <4 x float> %tmp536, <4 x float> zeroinitializer, <4 x i32> < i32 6, i32 7, i32 2, i32 3 >		; <<4 x float>> [#uses=1]
	%tmp580 = bitcast <4 x float> %tmp542 to <4 x i32>		; <<4 x i32>> [#uses=1]
	%tmp582 = and <4 x i32> %tmp580, zeroinitializer		; <<4 x i32>> [#uses=1]
	%tmp591 = or <4 x i32> %tmp582, zeroinitializer		; <<4 x i32>> [#uses=1]
	%tmp592 = bitcast <4 x i32> %tmp591 to <4 x float>		; <<4 x float>> [#uses=1]
	%tmp609 = fdiv <4 x float> < float 1.000000e+00, float 1.000000e+00, float 1.000000e+00, float 1.000000e+00 >, %tmp592		; <<4 x float>> [#uses=1]
	%tmp652 = shufflevector <4 x float> %tmp609, <4 x float> undef, <4 x i32> < i32 3, i32 3, i32 3, i32 3 >		; <<4 x float>> [#uses=1]
	%tmp662 = fmul <4 x float> zeroinitializer, %tmp652		; <<4 x float>> [#uses=1]
	%tmp678 = shufflevector <4 x float> %tmp662, <4 x float> undef, <4 x i32> < i32 1, i32 1, i32 1, i32 1 >		; <<4 x float>> [#uses=1]
	%tmp753 = fmul <4 x float> zeroinitializer, %tmp678		; <<4 x float>> [#uses=1]
	%tmp754 = fsub <4 x float> zeroinitializer, %tmp753		; <<4 x float>> [#uses=1]
	store <4 x float> %tmp754, ptr null, align 16
	unreachable
}

; ---- from 2008-05-09-ShuffleLoweringBug.ll ----
define fastcc void @glgVectorFloatConversion_g196m3() nounwind  {
	%tmp12745 = load <4 x float>, ptr null, align 16		; <<4 x float>> [#uses=1]
	%tmp12773 = insertelement <4 x float> %tmp12745, float 1.000000e+00, i32 1		; <<4 x float>> [#uses=1]
	%tmp12774 = insertelement <4 x float> %tmp12773, float 0.000000e+00, i32 2		; <<4 x float>> [#uses=1]
	%tmp12775 = insertelement <4 x float> %tmp12774, float 1.000000e+00, i32 3		; <<4 x float>> [#uses=1]
	store <4 x float> %tmp12775, ptr null, align 16
	unreachable
}

; ---- from 2008-07-22-CombinerCrash.ll ----
; PR2566

@0 = external dso_local global i16		; <ptr>:0 [#uses=1]
@1 = external dso_local global <4 x i16>		; <ptr>:1 [#uses=1]

declare void @abort()

define void @t_g196m4() nounwind {
	load i16, ptr @0		; <i16>:1 [#uses=1]
	zext i16 %1 to i64		; <i64>:2 [#uses=1]
	bitcast i64 %2 to <4 x i16>		; <<4 x i16>>:3 [#uses=1]
	shufflevector <4 x i16> %3, <4 x i16> undef, <4 x i32> zeroinitializer		; <<4 x i16>>:4 [#uses=1]
	store <4 x i16> %4, ptr @1
	ret void
}

; ---- from 2008-10-16-VecUnaryOp.ll ----
; PR2762
define void @foo_g196m5(ptr %p, ptr %q) {
  %n = load <4 x i32>, ptr %p
  %z = sitofp <4 x i32> %n to <4 x double>
  store <4 x double> %z, ptr %q
  ret void
}

; ---- from 2009-03-26-NoImplicitFPBug.ll ----
define double @t_g196m6(double %x) nounwind ssp noimplicitfloat {
entry:
	br i1 false, label %return, label %bb3

bb3:		; preds = %entry
	ret double 0.000000e+00

return:		; preds = %entry
	ret double undef
}

; ---- from vec_zero-2.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define i32 @t_g196m7() {
entry:
	br i1 true, label %bb4743, label %bb1656
bb1656:		; preds = %entry
	ret i32 0
bb1664:		; preds = %entry
	br i1 false, label %bb5310, label %bb4743
bb4743:		; preds = %bb1664
	%tmp5256 = bitcast <2 x i64> zeroinitializer to <8 x i16>		; <<8 x i16>> [#uses=1]
	%tmp5257 = sub <8 x i16> %tmp5256, zeroinitializer		; <<8 x i16>> [#uses=1]
	%tmp5258 = bitcast <8 x i16> %tmp5257 to <2 x i64>		; <<2 x i64>> [#uses=1]
	%tmp5265 = bitcast <2 x i64> %tmp5258 to <8 x i16>		; <<8 x i16>> [#uses=1]
	%tmp5266 = call <16 x i8> @llvm.x86.sse2.packuswb.128( <8 x i16> %tmp5265, <8 x i16> zeroinitializer ) nounwind readnone 		; <<8 x i16>> [#uses=1]
	%tmp5267 = bitcast <16 x i8> %tmp5266 to <2 x i64>		; <<2 x i64>> [#uses=1]
	%tmp5294 = and <2 x i64> zeroinitializer, %tmp5267		; <<2 x i64>> [#uses=1]
	br label %bb5310
bb5310:		; preds = %bb4743, %bb1664
	%tmp5294.pn = phi <2 x i64> [ %tmp5294, %bb4743 ], [ zeroinitializer, %bb1664 ]		; <<2 x i64>> [#uses=0]
	ret i32 0
}

declare <16 x i8> @llvm.x86.sse2.packuswb.128(<8 x i16>, <8 x i16>) nounwind readnone

; ---- from vfcmp.ll ----
; PR2620


define void @t2_g196m8(i32 %m_task_id, i32 %start_x, i32 %end_x) nounwind {
	%A = fcmp olt <2 x double> zeroinitializer, zeroinitializer		; <<2 x i64>>:1 [#uses=1]
        sext <2 x i1> %A to <2 x i64>
	extractelement <2 x i64> %1, i32 1		; <i64>:2 [#uses=1]
	lshr i64 %2, 63		; <i64>:3 [#uses=1]
	trunc i64 %3 to i1		; <i1>:4 [#uses=1]
	zext i1 %4 to i8		; <i8>:5 [#uses=1]
	insertelement <2 x i8> zeroinitializer, i8 %5, i32 1		; <<2 x i8>>:6 [#uses=1]
	store <2 x i8> %6, ptr null
	ret void
}
