; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

; ---- from extractelement-legalization-cycle.ll ----
; When the extractelement is converted to a load the store can be re-used.
; This will, however, introduce a cycle into the selection DAG (the load
; of the extractelement index is dependent on the store, and so after the
; conversion it becomes dependent on the new load, which is dependent on
; the index).  Make sure we skip the store, and conservatively instead
; use a store to the stack.

define float @foo_g382m0(ptr %i, ptr %v) {
; CHECK-LABEL: foo_g382m0:
; CHECK:    movaps %xmm0, -[[OFFSET:[0-9]+]](%rsp)
; CHECK:    movss -[[OFFSET]](%rsp,{{.*}}), %xmm0 {{.*}}
; CHECK-NEXT:    retq
  %1 = load <4 x float>, ptr %v, align 16
  %mul = fmul <4 x float> %1, %1
  store <4 x float> %mul, ptr %v, align 16
  %2 = load i32, ptr %i, align 4
  %vecext = extractelement <4 x float> %mul, i32 %2
  ret float %vecext
}

; ---- from imul-lea-2.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py


define i64 @t1_g382m1(i64 %a) nounwind readnone {
; CHECK-LABEL: t1_g382m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    leaq (%rdi,%rdi,8), %rax
; CHECK-NEXT:    leaq (%rax,%rax,8), %rax
; CHECK-NEXT:    retq
entry:
  %0 = mul i64 %a, 81
  ret i64 %0
}

define i64 @t2_g382m1(i64 %a) nounwind readnone {
; CHECK-LABEL: t2_g382m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    shlq $3, %rdi
; CHECK-NEXT:    leaq (%rdi,%rdi,4), %rax
; CHECK-NEXT:    retq
entry:
  %0 = mul i64 %a, 40
  ret i64 %0
}

; ---- from inline-asm-2addr.ll ----
define i64 @t_g382m2(i64 %a, i64 %b) nounwind ssp {
entry:
; CHECK-LABEL: t_g382m2:
	%asmtmp = tail call i64 asm "rorq $1,$0", "=r,J,0,~{dirflag},~{fpsr},~{flags},~{cc}"(i32 1, i64 %a) nounwind		; <i64> [#uses=1]
; CHECK:      #APP
; CHECK-NEXT: rorq    %[[REG1:.*]]
; CHECK-NEXT: #NO_APP
	%asmtmp1 = tail call i64 asm "rorq $1,$0", "=r,J,0,~{dirflag},~{fpsr},~{flags},~{cc}"(i32 1, i64 %b) nounwind		; <i64> [#uses=1]
; CHECK-NEXT: #APP
; CHECK-NEXT: rorq    %[[REG2:.*]]
; CHECK-NEXT: #NO_APP
	%0 = add i64 %asmtmp1, %asmtmp		; <i64> [#uses=1]
; CHECK-NEXT: leaq    (%[[REG2]],%[[REG1]]), %rax
	ret i64 %0
; CHECK:      retq
}

; ---- from pr39098.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3

define dso_local void @test_cancel2_g382m3(ptr %p1, ptr %p2) {
; CHECK-LABEL: test_cancel2_g382m3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl (%rdi), %eax
; CHECK-NEXT:    shrl %eax
; CHECK-NEXT:    andl $524287, %eax # imm = 0x7FFFF
; CHECK-NEXT:    movl %eax, (%rsi)
; CHECK-NEXT:    movb $0, 4(%rsi)
; CHECK-NEXT:    retq
entry:
  %0 = load i40, ptr %p1, align 8
  %shl414 = shl i40 %0, 19
  %unsclear415 = and i40 %shl414, 549755813887
  %shr416 = lshr i40 %unsclear415, 20
  %unsclear417 = and i40 %shr416, 549755813887
  store i40 %unsclear417, ptr %p2, align 8
  ret void
}

; ---- from prologuedata.ll ----
@i_g382m4 = linkonce_odr global i32 1

; CHECK: f_g382m4:
; CHECK-NEXT: .cfi_startproc
; CHECK-NEXT: .long	1
define void @f_g382m4() prologue i32 1 {
  ret void
}

; CHECK: g_g382m4:
; CHECK-NEXT: .cfi_startproc
; CHECK-NEXT: .quad	i_g382m4
define void @g_g382m4() prologue ptr @i_g382m4 {
  ret void
}

; ---- from shuffle-combine-crash-3.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; Verify that we don't crash when compiling this. We used to hit an
; assert like this
;
;   llc: ../include/llvm/CodeGen/ValueTypes.h:251: llvm::MVT llvm::EVT::getSimpleVT() const: Assertion `isSimple() && "Expected a SimpleValueType!"' failed.
;
; due to getFauxShuffleMask not checking that the VT was simple before a call
; to getSimpleValueType().

define i1 @dont_hit_assert_g382m5(i24 signext %d) {
; CHECK-LABEL: dont_hit_assert_g382m5:
; CHECK:       # %bb.0: # %for.cond
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    retq
for.cond:
  %t0 = insertelement <8 x i24> zeroinitializer, i24 1, i32 0
  %t5 = icmp slt <8 x i24> %t0, zeroinitializer
  %t7 = icmp slt i24 0, %d
  %rdx.shuf = shufflevector <8 x i1> %t5, <8 x i1> undef, <8 x i32> <i32 4, i32 5, i32 6, i32 7, i32 undef, i32 undef, i32 undef, i32 undef>
  %bin.rdx = and <8 x i1> %t5, %rdx.shuf
  %rdx.shuf22 = shufflevector <8 x i1> %bin.rdx, <8 x i1> undef, <8 x i32> <i32 2, i32 3, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
  %bin.rdx23 = and <8 x i1> %bin.rdx, %rdx.shuf22
  %rdx.shuf24 = shufflevector <8 x i1> %bin.rdx23, <8 x i1> undef, <8 x i32> <i32 1, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
  %bin.rdx25 = and <8 x i1> %bin.rdx23, %rdx.shuf24
  %t8 = extractelement <8 x i1> %bin.rdx25, i32 0
  ret i1 %t8
}

; ---- from vec_unsafe-fp-math.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; Make sure that vectors get the same benefits as scalars when using unsafe-fp-math.

; Subtracting zero is free.
define <4 x float> @vec_fsub_zero_g382m6(<4 x float> %x) {
; CHECK-LABEL: vec_fsub_zero_g382m6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    retq
  %sub = fsub <4 x float> %x, zeroinitializer
  ret <4 x float> %sub
}

; Negating doesn't require subtraction.
define <4 x float> @vec_fneg_g382m6(<4 x float> %x) {
; CHECK-LABEL: vec_fneg_g382m6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorps {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %sub = fsub nsz <4 x float> zeroinitializer, %x
  ret <4 x float> %sub
}
