; RUN: llc < %s -mtriple=i686-unknown-linux-gnu | FileCheck %s

; ---- from sext-ret-val.ll ----
; rdar://6699246

define signext i8 @t1_g243m0(ptr %A) nounwind readnone ssp {
entry:
        %0 = icmp ne ptr %A, null
        %1 = zext i1 %0 to i8
        ret i8 %1

; CHECK-LABEL: t1_g243m0:
; CHECK: cmpl
; CHECK-NEXT: setne
; CHECK-NEXT: retl
}

define i8 @t2_g243m0(ptr %A) nounwind readnone ssp {
entry:
        %0 = icmp ne ptr %A, null
        %1 = zext i1 %0 to i8
        ret i8 %1

; CHECK-LABEL: t2_g243m0:
; CHECK: cmpl
; CHECK-NEXT: setne
; CHECK-NEXT: retl
}

; ---- from sext-trunc.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define signext i8 @foo_g243m1(i16 signext  %x) nounwind  {
; CHECK-LABEL: foo_g243m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    retl
	%retval56 = trunc i16 %x to i8
	ret i8 %retval56

}
