; RUN: llc < %s -mtriple=x86_64-apple-darwin -mcpu=knl | FileCheck %s

; ---- from avx512-build-vector.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define <16 x i32> @test2_g305m0(<16 x i32> %x) {
; CHECK-LABEL: test2_g305m0:
; CHECK:       ## %bb.0:
; CHECK-NEXT:    vpternlogd {{.*#+}} zmm1 = -1
; CHECK-NEXT:    vpaddd %zmm1, %zmm0, %zmm0
; CHECK-NEXT:    retq
   %res = add <16 x i32><i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1, i32 -1>, %x
   ret <16 x i32>%res
}

define <16 x float> @test3_g305m0(<4 x float> %a) {
; CHECK-LABEL: test3_g305m0:
; CHECK:       ## %bb.0:
; CHECK-NEXT:    ## kill: def $xmm0 killed $xmm0 def $zmm0
; CHECK-NEXT:    vxorps %xmm2, %xmm2, %xmm2
; CHECK-NEXT:    vmovaps {{.*#+}} zmm1 = [0,1,2,3,4,18,16,7,8,9,10,11,12,13,14,15]
; CHECK-NEXT:    vpermi2ps %zmm0, %zmm2, %zmm1
; CHECK-NEXT:    vmovaps %zmm1, %zmm0
; CHECK-NEXT:    retq
  %b = extractelement <4 x float> %a, i32 2
  %c = insertelement <16 x float> <float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float undef, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00>, float %b, i32 5
  %b1 = extractelement <4 x float> %a, i32 0
  %c1 = insertelement <16 x float> %c, float %b1, i32 6
  ret <16 x float>%c1
}

; ---- from avx512-inc-dec.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define i32 @test_g305m1(i32 %a, i32 %b) {
; CHECK-LABEL: test_g305m1:
; CHECK:       ## %bb.0:
; CHECK-NEXT:    ## kill: def $esi killed $esi def $rsi
; CHECK-NEXT:    ## kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    leal -1(%rdi), %ecx
; CHECK-NEXT:    leal 1(%rsi), %eax
; CHECK-NEXT:    imull %ecx, %eax
; CHECK-NEXT:    retq
 %a1 = add i32 %a, -1
 %b1 = add i32 %b, 1
 %res = mul i32 %a1, %b1
 ret i32 %res
}

; ---- from avx512-vselect-crash.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define <16 x i32> @test_g305m2() {
; CHECK-LABEL: test_g305m2:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    retq
entry:
  %0 = icmp slt <16 x i32> undef, undef
  %1 = select <16 x i1> %0, <16 x i32> undef, <16 x i32> zeroinitializer
  ret <16 x i32> %1
}

; ---- from i1narrowfail.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define void @foo_g305m3(ptr %ptr) {
; CHECK-LABEL: foo_g305m3:
; CHECK:       ## %bb.0:
; CHECK-NEXT:    orb $16, (%rdi)
; CHECK-NEXT:    retq
  %r11 = load i64, ptr %ptr, align 8
  %r12 = or i64 16, %r11
  store i64 %r12, ptr %ptr, align 8
  ret void
}

define void @foo_noalign_g305m3(ptr %ptr) {
; CHECK-LABEL: foo_noalign_g305m3:
; CHECK:       ## %bb.0:
; CHECK-NEXT:    orb $16, (%rdi)
; CHECK-NEXT:    retq
  %r11 = load i64, ptr %ptr, align 1
  %r12 = or i64 16, %r11
  store i64 %r12, ptr %ptr, align 1
  ret void
}
