; RUN: llc < %s -mattr=+avx -mtriple=i686-unknown-unknown | FileCheck %s

; ---- from 2012-01-11-split-cv.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define void @add18i16_g140m0(ptr nocapture sret(<18 x i16>) %ret, ptr %bp) nounwind {
; CHECK-LABEL: add18i16_g140m0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; CHECK-NEXT:    vmovups (%ecx), %ymm0
; CHECK-NEXT:    movl 32(%ecx), %ecx
; CHECK-NEXT:    movl %ecx, 32(%eax)
; CHECK-NEXT:    vmovups %ymm0, (%eax)
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retl $4
  %b = load <18 x i16>, ptr %bp, align 16
  %x = add <18 x i16> zeroinitializer, %b
  store <18 x i16> %x, ptr %ret, align 16
  ret void
}

; ---- from 2012-1-10-buildvector.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define void @bad_cast_g140m1() {
; CHECK-LABEL: bad_cast_g140m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovaps %xmm0, (%eax)
; CHECK-NEXT:    movl $0, (%eax)
; CHECK-NEXT:    retl
  %vext.i = shufflevector <2 x i64> undef, <2 x i64> undef, <3 x i32> <i32 0, i32 1, i32 undef>
  %vecinit8.i = shufflevector <3 x i64> zeroinitializer, <3 x i64> %vext.i, <3 x i32> <i32 0, i32 3, i32 4>
  store <3 x i64> %vecinit8.i, ptr undef, align 32
  ret void
}

define void @bad_insert_g140m1(i32 %t) {
; CHECK-LABEL: bad_insert_g140m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovss {{.*#+}} xmm0 = mem[0],zero,zero,zero
; CHECK-NEXT:    vmovaps %ymm0, (%eax)
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retl
  %v2 = insertelement <8 x i32> zeroinitializer, i32 %t, i32 0
  store <8 x i32> %v2, ptr addrspace(1) undef, align 32
  ret void
}
