; RUN: llc < %s -mtriple=i686-- -mcpu=yonah | FileCheck %s

; ---- from 2004-03-30-Select-Max.ll ----
; CHECK-NOT: {{j[lgbe]}}

define i32 @max_g217m0(i32 %A, i32 %B) nounwind {
        %gt = icmp sgt i32 %A, %B               ; <i1> [#uses=1]
        %R = select i1 %gt, i32 %A, i32 %B              ; <i32> [#uses=1]
        ret i32 %R
}

; ---- from compare_folding.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

declare i1 @llvm.isunordered.f64(double, double)
define i1 @test1_g217m1(double %X, double %Y) {
; CHECK-LABEL: test1_g217m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movsd {{.*#+}} xmm0 = mem[0],zero
; CHECK-NEXT:    ucomisd {{[0-9]+}}(%esp), %xmm0
; CHECK-NEXT:    setp %al
; CHECK-NEXT:    retl
        %COM = fcmp uno double %X, %Y           ; <i1> [#uses=1]
        ret i1 %COM
}

; ---- from isnan2.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; This should not need to materialize 0.0 to evaluate the condition.

define i32 @test_g217m2(double %X) nounwind  {
; CHECK-LABEL: test_g217m2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movsd {{.*#+}} xmm0 = mem[0],zero
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    ucomisd %xmm0, %xmm0
; CHECK-NEXT:    setp %al
; CHECK-NEXT:    retl
entry:
	%tmp6 = fcmp uno double %X, 0.000000e+00		; <i1> [#uses=1]
	%tmp67 = zext i1 %tmp6 to i32		; <i32> [#uses=1]
	ret i32 %tmp67
}

; ---- from vshift_split2.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; Legalization example that requires splitting a large vector into smaller pieces.

define void @update_g217m3(<8 x i32> %val, ptr %dst) nounwind {
; CHECK-LABEL: update_g217m3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    psrad $2, %xmm0
; CHECK-NEXT:    psrad $4, %xmm1
; CHECK-NEXT:    movdqa %xmm1, 16(%eax)
; CHECK-NEXT:    movdqa %xmm0, (%eax)
; CHECK-NEXT:    retl
entry:
	%shl = shl <8 x i32> %val, < i32 2, i32 2, i32 2, i32 2, i32 4, i32 4, i32 4, i32 4 >
	%shr = ashr <8 x i32> %val, < i32 2, i32 2, i32 2, i32 2, i32 4, i32 4, i32 4, i32 4 >
	store <8 x i32> %shr, ptr %dst
	ret void
}
