; RUN: llc < %s -mtriple=i686-- -mattr=+sse2 | FileCheck %s

; ---- from 2007-05-17-ShuffleISelBug.ll ----
; CHECK-NOT: punpckhwd

declare <16 x i8> @llvm.x86.sse2.packuswb.128(<8 x i16>, <8 x i16>)

declare <8 x i16> @llvm.x86.sse2.psrl.w(<8 x i16>, <8 x i16>)

define fastcc void @test_g199m0(ptr %src, i32 %sbpr, ptr %dst, i32 %dbpr, i32 %w, i32 %h, i32 %dstalpha, i32 %mask) {
	%tmp633 = shufflevector <8 x i16> zeroinitializer, <8 x i16> undef, <8 x i32> < i32 4, i32 4, i32 5, i32 5, i32 6, i32 6, i32 7, i32 7 >
	%tmp715 = mul <8 x i16> zeroinitializer, %tmp633
	%tmp776 = bitcast <8 x i16> %tmp715 to <4 x i32>
	%tmp777 = add <4 x i32> %tmp776, shufflevector (<4 x i32> < i32 65537, i32 0, i32 0, i32 0 >, <4 x i32> < i32 65537, i32 0, i32 0, i32 0 >, <4 x i32> zeroinitializer)
	%tmp805 = add <4 x i32> %tmp777, zeroinitializer
	%tmp832 = bitcast <4 x i32> %tmp805 to <8 x i16>
	%tmp838 = tail call <8 x i16> @llvm.x86.sse2.psrl.w( <8 x i16> %tmp832, <8 x i16> < i16 8, i16 undef, i16 undef, i16 undef, i16 undef, i16 undef, i16 undef, i16 undef > )
	%tmp1020 = tail call <16 x i8> @llvm.x86.sse2.packuswb.128( <8 x i16> zeroinitializer, <8 x i16> %tmp838 )
	%tmp1030 = bitcast <16 x i8> %tmp1020 to <4 x i32>
	%tmp1033 = add <4 x i32> zeroinitializer, %tmp1030
	%tmp1048 = bitcast <4 x i32> %tmp1033 to <2 x i64>
	%tmp1049 = or <2 x i64> %tmp1048, zeroinitializer
	store <2 x i64> %tmp1049, ptr null
	ret void
}

; ---- from 2008-06-25-VecISelBug.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define void @t_g199m1() nounwind  {
; CHECK-LABEL: t_g199m1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movaps {{.*#+}} xmm0 = [0.0E+0,0.0E+0,0.0E+0,1.0E+0]
; CHECK-NEXT:    movaps %xmm0, 0
entry:
	%tmp1 = shufflevector <4 x float> zeroinitializer, <4 x float> < float 0.000000e+00, float 1.000000e+00, float 0.000000e+00, float 1.000000e+00 >, <4 x i32> < i32 0, i32 1, i32 4, i32 5 >
	%tmp2 = insertelement <4 x float> %tmp1, float 1.000000e+00, i32 3
	store <4 x float> %tmp2, ptr null, align 16
	unreachable
}

; ---- from combine-lds.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define double @doload64_g199m2(i64 %x) nounwind  {
; CHECK-LABEL: doload64_g199m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fldl {{[0-9]+}}(%esp)
; CHECK-NEXT:    retl
	%tmp717 = bitcast i64 %x to double
	ret double %tmp717
}

; ---- from fp2sint.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;; LowerFP_TO_SINT should not create a stack object if it's not needed.


define i32 @main_g199m3(i32 %argc, ptr %argv) {
; CHECK-LABEL: main_g199m3:
; CHECK:       # %bb.0: # %cond_false.i.i.i
; CHECK-NEXT:    cvttsd2si 0, %eax
; CHECK-NEXT:    movl %eax, 0
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    retl
cond_false.i.i.i:               ; preds = %bb.i5
       %tmp35.i = load double, ptr null, align 8           ; <double> [#uses=1]
       %tmp3536.i = fptosi double %tmp35.i to i32              ; <i32> [#uses=1]
       %tmp3536140.i = zext i32 %tmp3536.i to i64              ; <i64> [#uses=1]
       %tmp39.i = load double, ptr null, align 4           ; <double> [#uses=1]
       %tmp3940.i = fptosi double %tmp39.i to i32              ; <i32> [#uses=1]
       %tmp3940137.i = zext i32 %tmp3940.i to i64              ; <i64> [#uses=1]
       %tmp3940137138.i = shl i64 %tmp3940137.i, 32            ; <i64> [#uses=1]
       %tmp3940137138.ins.i = or i64 %tmp3940137138.i, %tmp3536140.i           ; <i64> [#uses=1]
       %tmp95.i.i = trunc i64 %tmp3940137138.ins.i to i32              ; <i32> [#uses=1]
       store i32 %tmp95.i.i, ptr null, align 4
       ret i32 0
}

; ---- from fsxor-alignment.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; Don't fold the incoming stack arguments into the xorps instructions used
; to do floating-point negations, because the arguments aren't vectors
; and aren't vector-aligned.

define void @foo_g199m4(ptr %p, ptr %q, float %s, float %y) nounwind {
; CHECK-LABEL: foo_g199m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushl %esi
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; CHECK-NEXT:    movl $-2147483648, %edx # imm = 0x80000000
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %esi
; CHECK-NEXT:    xorl %edx, %esi
; CHECK-NEXT:    movl %esi, (%ecx)
; CHECK-NEXT:    xorl {{[0-9]+}}(%esp), %edx
; CHECK-NEXT:    movl %edx, (%eax)
; CHECK-NEXT:    popl %esi
; CHECK-NEXT:    retl
  %ss = fsub float -0.0, %s
  %yy = fsub float -0.0, %y
  store float %ss, ptr %p
  store float %yy, ptr %q
  ret void
}

; ---- from vshift_split.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; Example that requires splitting and expanding a vector shift.
define <2 x i64> @update_g199m5(<2 x i64> %val) nounwind readnone {
; CHECK-LABEL: update_g199m5:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movdqa %xmm0, %xmm1
; CHECK-NEXT:    psrlq $2, %xmm1
; CHECK-NEXT:    psrlq $3, %xmm0
; CHECK-NEXT:    movsd {{.*#+}} xmm0 = xmm1[0],xmm0[1]
; CHECK-NEXT:    retl
entry:
	%shr = lshr <2 x i64> %val, < i64 2, i64 3 >
	ret <2 x i64> %shr
}
