; RUN: llc -mtriple=x86_64-unknown-linux < %s | FileCheck %s

; ---- from pr196804.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; combineSelect's "select(~Cond, X, Y) -> select(Cond, Y, X)" was incorrectly
; firing on scalar selects. The stores block folds of or/xor to expose the bug.

define i32 @test_g93m0(i32 %arg, i8 %arg1, ptr %arg2, ptr %arg3) nounwind {
; CHECK-LABEL: test_g93m0:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    orb $-2, %sil
; CHECK-NEXT:    movb %sil, (%rcx)
; CHECK-NEXT:    notb %sil
; CHECK-NEXT:    movb %sil, (%rdx)
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    testb %sil, %sil
; CHECK-NEXT:    cmovnel %edi, %eax
; CHECK-NEXT:    retq
bb:
  %or = or i8 %arg1, -2
  store i8 %or, ptr %arg3, align 1
  %xor = xor i8 %or, -1
  store i8 %xor, ptr %arg2, align 1
  %icmp = icmp ne i8 %xor, 0
  %select = select i1 %icmp, i32 %arg, i32 0
  ret i32 %select
}

; ---- from pr63430.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --no_x86_scrub_sp --version 2

; Make sure the argument is read before the stack slot is over-written.
define i1 @test_g93m1(ptr %a0, ptr %a1, ptr %a2, ptr %a3, ptr %a4, ptr %a5, i128 %x) {
; CHECK-LABEL: test_g93m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq 8(%rsp), %rax
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    andq 16(%rsp), %rax
; CHECK-NEXT:    movaps %xmm0, 8(%rsp)
; CHECK-NEXT:    cmpq $-1, %rax
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    retq
  %alloca = alloca i128
  store i128 %x, ptr %alloca
  store i128 0, ptr %alloca
  %cmp = icmp eq i128 %x, -1
  ret i1 %cmp
}
