; RUN: llc -mtriple=x86_64-linux < %s | FileCheck %s

; ---- from dyn_alloca_aligned.ll ----
define i32 @A_g78m0(i32 %Size) {
; CHECK:  subq    %rcx, %rax
; CHECK:  andq    $-128, %rax
; CHECK:  movq    %rax, %rsp
  %A_g78m0 = alloca i8, i32 %Size, align 128
  %A_addr = ptrtoint ptr %A_g78m0 to i32
  ret i32 %A_addr
}

; ---- from opaque-ptr.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define void @okay_g78m1(ptr %p, i32 %x) nounwind {
; CHECK-LABEL: okay_g78m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    #APP
; CHECK-NEXT:    addl %esi, %eax
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    movl %eax, (%rdi)
; CHECK-NEXT:    retq
  call void asm "addl $1, $0", "=*r,r"(ptr elementtype(i32) %p, i32 %x)
  ret void
}

; ---- from sse-commute.ll ----
; Commute the comparison to avoid a_g78m2 move.
; PR7500.

; CHECK-LABEL: a_g78m2:
; CHECK-NOT: mov
; CHECK:     pcmpeqd
define <2 x double> @a_g78m2(<2 x double>, <2 x double>) nounwind readnone {
entry:
  %tmp6 = bitcast <2 x double> %0 to <4 x i32>    ; <<4 x i32>> [#uses=2]
  %tmp4 = bitcast <2 x double> %1 to <4 x i32>    ; <<4 x i32>> [#uses=1]
  %cmp = icmp eq <4 x i32> %tmp6, %tmp4           ; <<4 x i1>> [#uses=1]
  %sext = sext <4 x i1> %cmp to <4 x i32>         ; <<4 x i32>> [#uses=1]
  %and = and <4 x i32> %tmp6, %sext               ; <<4 x i32>> [#uses=1]
  %tmp8 = bitcast <4 x i32> %and to <2 x double>  ; <<2 x double>> [#uses=1]
  ret <2 x double> %tmp8
}

; ---- from tailcall-nofpclass.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; Ensures that taillcall optimization can still be
; performed when nofpclass is used.

define noundef nofpclass(nan inf) float @_Z3foof_g78m3(float noundef nofpclass(nan inf) %0) {
; CHECK-LABEL: _Z3foof_g78m3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jmp expf@PLT # TAILCALL
  %2 = tail call float @llvm.exp.f32(float %0)
  ret float %2
}
