; RUN: llc < %s -mtriple=x86_64-linux-gnu | FileCheck %s

; ---- from pr90668.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4

define i64 @off_g329m0(i8 signext %a) {
; CHECK-LABEL: off_g329m0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addb $-128, %dil
; CHECK-NEXT:    movzbl %dil, %eax
; CHECK-NEXT:    shll $3, %eax
; CHECK-NEXT:    retq
entry:
  %add = xor i8 %a, -128
  %conv2 = zext i8 %add to i64
  %mul = shl nuw nsw i64 %conv2, 3
  ret i64 %mul
}

; ---- from pr92569.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4

define void @PR92569_g329m1(i64 %arg, <8 x i8> %arg1) {
; CHECK-LABEL: PR92569_g329m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl $64, %eax
; CHECK-NEXT:    rep bsfq %rdi, %rax
; CHECK-NEXT:    shrb $3, %al
; CHECK-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movzbl %al, %eax
; CHECK-NEXT:    movzbl -24(%rsp,%rax), %eax
; CHECK-NEXT:    movl %eax, 0
; CHECK-NEXT:    retq
  %cttz = call i64 @llvm.cttz.i64(i64 %arg, i1 false)
  %trunc = trunc i64 %cttz to i8
  %lshr = lshr i8 %trunc, 3
  %extractelement = extractelement <8 x i8> %arg1, i8 %lshr
  %freeze = freeze i8 %extractelement
  %zext = zext i8 %freeze to i32
  store i32 %zext, ptr addrspace(1) null, align 4
  ret void
}

; ---- from pr92720.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; Make sure we don't crash when shrinking the shift amount before legalization.
define i64 @pr92720_g329m2(i64 %x) {
; CHECK-LABEL: pr92720_g329m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movabsq $8589934592, %rax # imm = 0x200000000
; CHECK-NEXT:    retq
  %or = or i64 %x, 255
  %sub = sub i64 0, %or
  %shl = shl i64 1, %sub
  %sext = shl i64 %shl, 32
  ret i64 %sext
}

; ---- from pr94824.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

define i16 @pr94824_g329m3(i8 %x1) {
; CHECK-LABEL: pr94824_g329m3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    orl $256, %edi # imm = 0x100
; CHECK-NEXT:    rep bsfl %edi, %ecx
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
entry:
  %cttz = call i8 @llvm.cttz.i8(i8 %x1, i1 false)
  %ext = zext i8 %cttz to i16
  %shl = shl i16 1, %ext
  ret i16 %shl
}
