; RUN: llc < %s -mcpu=generic -mtriple=x86_64-linux | FileCheck %s

; ---- from pr32588.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

@c = external dso_local local_unnamed_addr global i32, align 4
@b = external dso_local local_unnamed_addr global i32, align 4
@d = external dso_local local_unnamed_addr global i32, align 4

define void @fn1_g153m0() {
; CHECK-LABEL: fn1_g153m0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    cmpl $0, c(%rip)
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    movl %eax, d(%rip)
; CHECK-NEXT:    retq
  %t0 = load i32, ptr @c, align 4
  %tobool1 = icmp eq i32 %t0, 0
  %xor = zext i1 %tobool1 to i32
  %t1 = load i32, ptr @b, align 4
  %tobool2 = icmp ne i32 %t1, 0
  %t2 = load i32, ptr @d, align 4
  %tobool4 = icmp ne i32 %t2, 0
  %t3 = and i1 %tobool4, %tobool2
  %sub = sext i1 %t3 to i32
  %div = sdiv i32 %sub, 2
  %add = add nsw i32 %div, %xor
  store i32 %add, ptr @d, align 4
  ret void
}

; ---- from red-zone2.ll ----
; CHECK-LABEL: f0_g153m1:
; CHECK: subq
; CHECK: addq

define x86_fp80 @f0_g153m1(float %f) nounwind readnone noredzone {
entry:
	%0 = fpext float %f to x86_fp80		; <x86_fp80> [#uses=1]
	ret x86_fp80 %0
}
