; RUN: llc < %s -mtriple=x86_64-linux | FileCheck %s

; ---- from sse-align-0.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define <4 x float> @foo_g323m0(ptr %p, <4 x float> %x) nounwind {
; CHECK-LABEL: foo_g323m0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mulps (%rdi), %xmm0
; CHECK-NEXT:    retq
  %t = load <4 x float>, ptr %p
  %z = fmul <4 x float> %t, %x
  ret <4 x float> %z
}

define <2 x double> @bar_g323m0(ptr %p, <2 x double> %x) nounwind {
; CHECK-LABEL: bar_g323m0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mulpd (%rdi), %xmm0
; CHECK-NEXT:    retq
  %t = load <2 x double>, ptr %p
  %z = fmul <2 x double> %t, %x
  ret <2 x double> %z
}

; ---- from sse-align-3.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define void @foo_g323m1(ptr %p, <4 x float> %x) nounwind {
; CHECK-LABEL: foo_g323m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movaps %xmm0, (%rdi)
; CHECK-NEXT:    retq
  store <4 x float> %x, ptr %p
  ret void
}

define void @bar_g323m1(ptr %p, <2 x double> %x) nounwind {
; CHECK-LABEL: bar_g323m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movaps %xmm0, (%rdi)
; CHECK-NEXT:    retq
  store <2 x double> %x, ptr %p
  ret void
}

; ---- from sse-align-7.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define void @bar_g323m2(ptr %p, <2 x i64> %x) nounwind {
; CHECK-LABEL: bar_g323m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movaps %xmm0, (%rdi)
; CHECK-NEXT:    retq
  store <2 x i64> %x, ptr %p
  ret void
}
