; RUN: llc < %s -mtriple=i386-apple-darwin | FileCheck %s

; ---- from 2008-06-16-SubregsBug.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define i16 @test_g167m0(ptr %tmp179) nounwind  {
; CHECK-LABEL: test_g167m0:
; CHECK:       ## %bb.0:
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    movzwl (%eax), %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $64512, %ecx ## imm = 0xFC00
; CHECK-NEXT:    negw %cx
; CHECK-NEXT:    jno LBB0_2
; CHECK-NEXT:  ## %bb.1: ## %bb189
; CHECK-NEXT:    ## kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retl
; CHECK-NEXT:  LBB0_2: ## %bb288
; CHECK-NEXT:    movw $32, %ax
; CHECK-NEXT:    retl
	%tmp180 = load i16, ptr %tmp179, align 2		; <i16> [#uses=2]
	%tmp184 = and i16 %tmp180, -1024		; <i16> [#uses=1]
	%tmp186 = icmp eq i16 %tmp184, -32768		; <i1> [#uses=1]
	br i1 %tmp186, label %bb189, label %bb288

bb189:		; preds = %0
	ret i16 %tmp180

bb288:		; preds = %0
	ret i16 32
}

; ---- from 2010-10-08-cmpxchg8b.ll ----
; PR8297
;
; On i386, i64 cmpxchg is lowered during legalize types to extract the
; 64-bit result into a pair of fixed regs. So creation of the DAG node
; happens in a different place. See
; X86TargetLowering::ReplaceNodeResults, case ATOMIC_CMP_SWAP.
;
; Neither Atomic-xx.ll nor atomic_op.ll cover this. Those tests were
; autogenerated from C source before 64-bit variants were supported.
;
; Note that this case requires a loop around the cmpxchg to force
; machine licm to query alias anlysis, exposing a bad
; MachineMemOperand.
define void @foo_g167m1(ptr %ptr) nounwind inlinehint {
entry:
  br label %loop
loop:
; CHECK: lock cmpxchg8b
  %pair = cmpxchg ptr %ptr, i64 0, i64 1 monotonic monotonic
  %r = extractvalue { i64, i1 } %pair, 0
  %stored1  = icmp eq i64 %r, 0
  br i1 %stored1, label %loop, label %continue
continue:
  ret void
}

; ---- from cstring.ll ----
; rdar://6479858

; CHECK-NOT: comm
@str1_g167m2 = internal constant [1 x i8] zeroinitializer

; ---- from fold-call-2.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

@f = external global ptr		; <ptr> [#uses=1]

define i32 @main_g167m3() nounwind {
; CHECK-LABEL: main_g167m3:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    subl $12, %esp
; CHECK-NEXT:    movl L_f$non_lazy_ptr, %eax
; CHECK-NEXT:    calll *(%eax)
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    addl $12, %esp
; CHECK-NEXT:    retl
entry:
	load ptr, ptr @f, align 8		; <ptr>:0 [#uses=1]
	tail call void %0( ) nounwind
	ret i32 0
}
