; RUN: llc < %s -mtriple=x86_64-- -mattr=+sse2 | FileCheck %s

; ---- from 2007-06-28-X86-64-isel.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define void @test_g274m0() {
; CHECK-LABEL: test_g274m0:
; CHECK:       # %bb.0: # %bb2
; CHECK-NEXT:    retq
	%tmp1 = call <8 x i16> @llvm.smin.v8i16( <8 x i16> zeroinitializer, <8 x i16> bitcast (<4 x i32> < i32 7, i32 7, i32 7, i32 7 > to <8 x i16>) )
	%tmp2 = bitcast <8 x i16> %tmp1 to <4 x i32>
	br i1 false, label %bb1, label %bb2

bb2:
	%tmp38007.i = extractelement <4 x i32> %tmp2, i32 3
	ret void

bb1:
	ret void
}

declare <8 x i16> @llvm.smin.v8i16(<8 x i16>, <8 x i16>)

; ---- from shrink-fp-const1.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; PR1264

define double @foo_g274m1(double %x) {
; CHECK-LABEL: foo_g274m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mulsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
        %y = fmul double %x, 5.000000e-01
        ret double %y
}
