; RUN: llc -mtriple=x86_64-- < %s | FileCheck %s

; ---- from build-vector-known-bits-poison.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6

; Test that computeKnownBits treats poison elements aggressively.

define <4 x i8> @poison_build_vector_known_bits_g70m0(<4 x i32> %v) {
; CHECK-LABEL: poison_build_vector_known_bits_g70m0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    pcmpgtd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    packssdw %xmm0, %xmm0
; CHECK-NEXT:    packsswb %xmm0, %xmm0
; CHECK-NEXT:    psllw $7, %xmm0
; CHECK-NEXT:    pxor %xmm1, %xmm1
; CHECK-NEXT:    pcmpgtb %xmm0, %xmm1
; CHECK-NEXT:    por {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    pand {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    movdqa %xmm1, %xmm0
; CHECK-NEXT:    retq
  %icmp = icmp ugt <4 x i32> %v, splat (i32 -9)
  %zext8 = zext <4 x i1> %icmp to <4 x i8>
  %shl = shl <4 x i8> splat (i8 11), %zext8
  %or = or <4 x i8> %shl, splat (i8 11)
  ret <4 x i8> %or
}

; ---- from pr23664.ll ----
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

define i2 @f_g70m1(i32 %arg) {
; CHECK-LABEL: f_g70m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    leal (%rdi,%rdi), %eax
; CHECK-NEXT:    incb %al
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
  %trunc = trunc i32 %arg to i1
  %sext = sext i1 %trunc to i2
  %or = or i2 %sext, 1
  ret i2 %or
}
