name: Release Binaries All

permissions:
  contents: read # Default everything to read-only

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release Version'
        required: true
        type: string
      upload:
        description: 'Upload binaries to the release page'
        required: true
        default: false
        type: boolean

  workflow_call:
    inputs:
      release-version:
        description: 'Release Version'
        required: true
        type: string
      upload:
        description: 'Upload binaries to the release page'
        required: true
        default: false
        type: boolean
    secrets:
      RELEASE_TASKS_USER_TOKEN:
        description: "Secret used to check user permissions."
        required: false

concurrency:
  group: ${{ github.workflow }}-dispatch
  cancel-in-progress: True

jobs:
  setup-variables:
    runs-on: ubuntu-24.04
    outputs:
      release-version: ${{ steps.vars.outputs.release-version }}
      upload: ${{ steps.vars.outputs.upload }}
    steps:
      - shell: bash
        id: vars
        run: |
          echo "release-version=${{ inputs.release-version }}" >> "$GITHUB_OUTPUT"
          echo "upload=${{ inputs.upload }}" >> "$GITHUB_OUTPUT"

  release-binaries-all:
    name: Build Release Binaries
    needs:
      - setup-variables
    permissions:
      contents: write # For release uploads
      id-token: write     # For artifact attestations
      attestations: write # For artifact attestations
    strategy:
      fail-fast: false
      matrix:
        # We use ubuntu-22.04 rather than the latest version to make the built
        # binaries more portable (eg functional aginast older glibc).
        runs-on:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-14
          - windows-2022
          - windows-11-arm

    uses: ./.github/workflows/release-binaries.yml
    with:
      release-version: "${{ needs.setup-variables.outputs.release-version }}"
      upload: ${{ needs.setup-variables.outputs.upload == 'true'}}
      runs-on: "${{ matrix.runs-on }}"
    secrets:
      RELEASE_TASKS_USER_TOKEN: ${{ secrets.RELEASE_TASKS_USER_TOKEN }}
